name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: get deps
        run: sudo apt-get install gcc-multilib
      - name: compile lc0 with OS-provided compiler
        run: make lc0
      - name: compilation tests
        run: make test
      - name: compile lc1 with lc0
        run: make lc1
      - name: compile lc with lc1
        run: make lc
      - name: compare results
        run: |
          sha256sum lc1.s lc
          diff lc1.s lc.s
